---
name: Update a GitHub Project
on:
  workflow_dispatch: {}
  # schedule:
    # - cron: "*/10 * * * *"
jobs:
  update-project:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - id: token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: aquaproj/aqua-installer@9ebf656952a20c45a5d66606f083ff34f58b8ce0 # v4.0.0
        with:
          aqua_version: v2.51.2
        env:
          GITHUB_TOKEN: ${{ steps.token.outputs.token }}
      - run: ghproj -v
        env:
          GITHUB_TOKEN: ${{ steps.token.outputs.token }}
      - run: ghproj add
        env:
          GITHUB_TOKEN: ${{ steps.token.outputs.token }}
